"""add_print_order_job_models

Revision ID: 6e251b570fd6
Revises: f30d774e83af
Create Date: 2026-08-23 00:17:05.984571

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6e251b570fd6"
down_revision: Union[str, Sequence[str], None] = "f30d774e83af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

print_order_states = postgresql.ENUM(
    "PENDING",
    "CONFIRMED",
    "DELIVRED",
    "CANCELLED",
    name="printorderstate",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    print_order_states.create(
        op.get_bind(),
        checkfirst=True,
    )

    op.create_table(
        "print_orders",
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "CONFIRMED",
                "DELIVRED",
                "CANCELLED",
                name="printorderstate",
                create_type=False,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "print_jobs",
        sa.Column("print_order_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["print_order_id"],
            ["print_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("print_jobs")
    op.drop_table("print_orders")
    # ### end Alembic commands ###
    print_order_states.drop(
        op.get_bind(),
        checkfirst=True,
    )
