"""add_job_status_product_id_print_job_model

Revision ID: dbe1a8b1c9ce
Revises: 6e251b570fd6
Create Date: 2026-08-24 22:52:51.136248

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dbe1a8b1c9ce"
down_revision: Union[str, Sequence[str], None] = "6e251b570fd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


print_job_states = postgresql.ENUM(
    "PENDING",
    "WAIT_FOR_PRINTING",
    "READY",
    "CANCELLED",
    name="printjobstate",
)


def upgrade() -> None:
    """Upgrade schema."""

    print_job_states.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("print_jobs", sa.Column("product_id", sa.UUID(), nullable=True))
    op.add_column(
        "print_jobs",
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "WAIT_FOR_PRINTING",
                "READY",
                "CANCELLED",
                name="printjobstate",
                create_type=False,
            ),
            nullable=False,
            server_default="PENDING",
        ),
    )
    op.alter_column(
        "print_jobs",
        "print_order_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.create_foreign_key(None, "print_jobs", "products", ["product_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "print_jobs", type_="foreignkey")
    op.alter_column(
        "print_jobs",
        "print_order_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.drop_column("print_jobs", "status")
    op.drop_column("print_jobs", "product_id")
    # ### end Alembic commands ###
    print_job_states.drop(
        op.get_bind(),
        checkfirst=True,
    )
