"""add_status_product_model

Revision ID: f30d774e83af
Revises: 47105f8114c9
Create Date: 2026-08-22 23:20:14.413005

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f30d774e83af"
down_revision: Union[str, Sequence[str], None] = "47105f8114c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


product_state_enum = postgresql.ENUM(
    "AVAILABLE",
    "OUT_OF_STOCK",
    "NON_AVAILABLE",  # <-- your real enum values, in order
    name="productstate",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    product_state_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "products",
        sa.Column(
            "status",
            postgresql.ENUM(
                "AVAILABLE",
                "OUT_OF_STOCK",
                "NON_AVAILABLE",
                name="productstate",
                create_type=False,
            ),
            nullable=False,
            server_default="AVAILABLE",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "status")
    # ### end Alembic commands ###
    product_state_enum.drop(op.get_bind(), checkfirst=True)
